name: Docker Build and Push Images
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: fedora/37
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -t weitherapp:0.0.1 -t ailogos/weitherapp:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push docker image
        run: docker push ailogos/weitherapp:0.0.1

